
all : 
	cd entree/ ; make essai; cd ..
	cd lexico/ ; make essai; cd ..
	cd symboles/ ; make essai ; cd ..
	cd pile/ ; make ; cd ..
	cd doublet/ ; make essai ; cd ..
	cd eval/  ; make ; cd ..
	cd fnum/ ; make ; cd ..
	cd flist/ ; make ; cd ..
	cd utiles/ ; make ; cd ..
	cd syntax/ ; make essai_e;cd  ..
